<?php

function ows_preprocess_html(&$variables) {
	$variables['page']['#attached']['library'][] = 'modal/modal';
	$variables['page']['#attached']['library'][] = 'core/drupal.ajax';
}

function ows_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if($form_id == "user_register_form") {
		//kint($form);
		/*$form['#attached']['library'][] = 'core/drupal.dialog.ajax';
		
		$form['actions'] = array();
		$form['actions']['#type'] = 'actions';
        $form['actions']['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Register',
            '#ajax' => array(
                //'callback' => '::submitForm'
            )
        );*/
	}
}
