<?php

function ows_preprocess_html(&$variables) {
	$variables['page']['#attached']['library'][] = 'modal/modal';
	$variables['page']['#attached']['library'][] = 'core/drupal.ajax';
}

function ows_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if($form_id == "user_register_form") {
		//kint($form);
		/*$form['#attached']['library'][] = 'core/drupal.dialog.ajax';
		
		$form['actions'] = array();
		$form['actions']['#type'] = 'actions';
        $form['actions']['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Register',
            '#ajax' => array(
                //'callback' => '::submitForm'
            )
        );*/
	}

	if ($form_id == "views_exposed_form" && $form['#id'] == "views-exposed-form-browse-page-browse") {
		// kint($form);
	}

	if ($form_id == "user_form") {
		$roles = $user = \Drupal::currentUser()->getRoles();
		$is_admin = false;
        if (in_array('administrator', $roles)) {
            $is_admin = true;
        }

		// dpm($form);
		// disable fields
		if (!$is_admin) {
			$form['account']['mail']['#disabled'] = TRUE;
			unset($form['account']['mail']['#description']);

			$form['account']['name']['#disabled'] = TRUE;
			unset($form['account']['name']['#description']);

			$form['account']['status']['#disabled'] = TRUE;
			$form['account']['roles']['#disabled'] = TRUE;
			$form['account']['notify']['#disabled'] = TRUE;
			$form['contact']['#disabled'] = TRUE;

			unset($form['account']['status']);
			unset($form['account']['roles']);
			unset($form['account']['notify']);
			unset($form['contact']);
		}
	}
}

function ows_views_query_alter(Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\Sql $query) {
	if ($view->current_display == "page_browse") {
		// filter by age
		// unset default where condition of birthday
		unset($query->where[1]['conditions'][1]);
		
		if (isset($_POST['age']) && $_POST['age'] > 0) {
			$configuration = [
				'table' => 'user__field_birthday',
				'field' => 'entity_id',
				'left_table' => 'users_field_data',
				'left_field' => 'uid',
				'operator' => '='
		    ];

		    $year = date('Y') - $_POST['age'];

			$join = \Drupal\views\Views::pluginManager('join')->createInstance('standard', $configuration);
			$query->addRelationship('user__field_birthday', $join, 'users_field_data');
			$query->addWhere(count($query->where), 'user__field_birthday.field_birthday_value', array("$year-01-01", "$year-12-31"), "BETWEEN");
			//$query->addWhere(count($query->where), 'user__field_birthday.field_birthday_value', "$year-01-01", ">=");
			//dpm($query);
		}
	}

	// Use session to pass search key
	if ($view->current_display == "page_search_user") {
		$current_path = \Drupal::service('path.current')->getPath();
		$path_args = explode('/', $current_path);

		$key = @$_SESSION['search-key']; // works

		$tempstore = \Drupal::service('user.private_tempstore')->get('ows');
		$key = $tempstore->get('search-key');

		if ($key) {
			$configuration = [
				'table' => 'user__field_first_name',
				'field' => 'entity_id',
				'left_table' => 'users_field_data',
				'left_field' => 'uid',
				'operator' => '='
		    ];

		    // new where group 
		    $group = 'name';
			$join = \Drupal\views\Views::pluginManager('join')->createInstance('standard', $configuration);
			$query->addRelationship('user__field_first_name', $join, 'users_field_data');
			$query->addWhere($group, 'user__field_first_name.field_first_name_value', $key.'%', "LIKE");

			$configuration = [
				'table' => 'user__field_last_name',
				'field' => 'entity_id',
				'left_table' => 'users_field_data',
				'left_field' => 'uid',
				'operator' => '='
		    ];

			$join = \Drupal\views\Views::pluginManager('join')->createInstance('standard', $configuration);
			$query->addRelationship('user__field_last_name', $join, 'users_field_data');
			$query->addWhere($group, 'user__field_last_name.field_last_name_value', $key.'%', "LIKE");

			// change group type to OR
			$view->query->where[$group]['type'] = 'OR';
		}
	}
}

function ows_mail($key, &$message, $params) {
	$options = array(
		'langcode' => $message['langcode'],
	);

	switch ($key) {
		case 'invite_friend':
			$message['from'] = \Drupal::config('system.site')->get('mail');
			$message['subject'] = t('@title', array('@title' => $params['title']), $options);
			$message['body'][] = $params['message'];
		break;
	}

	switch ($key) {
		// send email to owner when someone submit Add Me form
		case 'add_me':
			$message['from'] = \Drupal::config('system.site')->get('mail');
			$message['subject'] = t('@title', array('@title' => $params['title']), $options);
			$message['body'][] = $params['message'];
		break;

		// send thanks email to sender
		case 'add_me_sender':
			$message['from'] = \Drupal::config('system.site')->get('mail');
			$message['subject'] = t('@title', array('@title' => $params['title']), $options);
			$message['body'][] = $params['message'];
		break;
	}
}
