<?php

/**
 * @file
 * Functions to support theming in the OWS theme.
 */

use Drupal\Core\Template\Attribute;

function ows_theme_preprocess_page(&$variables) {
}

function ows_theme_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
	// $path_args = \Drupal::routeMatch()->getRouteName();
	// if ($path_args == "ows.ajax_content") {}
	// $suggestions[] = $hook . '__' . 'logged_in';
}
