<?php

function free_quote_menu() {
	// ------ display 3 forms on a page, user javascript to switch ------
	$items['free-quote-submit'] = array(
		'title' => t(''),
		'page callback' => '_free_quote_submit',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['add-to-quote'] = array(
		'title' => t(''),
		'page callback' => '_add_to_quote',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['submit-quote'] = array(
		'title' => t(''),
		'page callback' => '_submit_quote_list',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['my-quote'] = array(
		'title' => t(''),
		'page callback' => '_my_quote',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['add-to-list'] = array(
		'title' => t(''),
		'page callback' => '_add_to_list',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items['my-quote/remove/%'] = array(
		'title' => t(''),
		'page callback' => '_remove_quote',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
		'page arguments' => array(2)
	);

	return $items;
}

function _add_to_list() {
	session_start();
	$ids = trim($_POST['ids'], '|');
	$ids = explode('|', $ids);

	$quantities = trim($_POST['quantities'], '|');
	$quantities = explode('|', $quantities);

	for($i = 0; $i < count($ids); $i++) {
		if ($ids[$i] && is_numeric($ids[$i])) {
			$n = node_load($ids[$i]);
			//$products_string .= 'Product: '.$n->title.' | Quantity: '.$quantities[$i].'<br>';
			$_SESSION['quote_list'][$ids[$i]] = array($n->title, $quantities[$i]);

			if (!$quantities[$i]) unset($_SESSION['quote_list'][$pid]);
		}
	}	
}

function _add_to_quote() {
	session_start();
	$nid = $_POST['id'];
	$quantity = $_POST['quantity'];

	if ($nid && $quantity) {
		if (!isset($_SESSION['quote_list'])) {
			$_SESSION['quote_list']	= array();
		}

		$n = node_load($nid);
		$_SESSION['quote_list'][$nid] = array($n->title, $quantity);
		print 1;
		exit();
	}

	print 0;
	exit();
}


function _remove_quote($pid) {
	if (isset($_SESSION['quote_list'][$pid])) {
		unset($_SESSION['quote_list'][$pid]);
		drupal_set_message("Produc has been removed from quote list");
	}

	drupal_goto("my-quote");
}

function _my_quote() {
	$html = '';
	$flag = true;

	if (isset($_SESSION['quote_list'])) { // isset($_SESSION['quote_email'])
		$header = array('Code', 'Product', 'Category', 'Image', 'Description', 'Brochure', 'Dimensions', 'Quantity', 'Action');
		$rows = array();	  

		$mail_body = '';
		$items = $_SESSION['quote_list'];
		foreach($items as $t => $v) {
			$n = node_load($t);
			if ($n->nid) {
				$category = '';
				if (isset($n->field_category['und'][0]['tid'])) {
					$term = taxonomy_term_load($n->field_category['und'][0]['tid']);
					$category = $term->name;
				}

				$img = '';
				if (isset($n->field_product_image['und'][0]['uri'])) {
					$img = theme('image_style',array('style_name' => '120', 'path' => $n->field_product_image['und'][0]['uri']));
				}

				$brochure = '';
				if (isset($n->field_brochure['und'][0]['uri'])) {
					$brochure = file_create_url($n->field_brochure['und'][0]['uri']);
				}

				$body = '';
				if (isset($n->body['und'][0]['value'])) {
					$body = $n->body['und'][0]['value'];
				}

				$mail_body .= '
					<div>Code: '.$n->field_product_code['und'][0]['value'].'</div>
					<div>Product: '.$n->title.'</div>
					<div>Category: '.$category.'</div>
					<div>Description: '.$body.'</div>
					<div>Brochure: '.$brochure.'</div>
					<div>Dimensions: '.$n->field_dimensions['und'][0]['value'].'</div>
					<div>Quantity: '.$v[1].'</div>';

				$rows[] = array(
					$n->field_product_code['und'][0]['value'],
					$n->title,
					$category,
					$img,
					$body,
					$brochure,
					@$n->field_dimensions['und'][0]['value'],
					$v[1], 
					l('Remove', 'my-quote/remove/'.$t));
			}
		}

		$html = theme('table', array('header' => $header, 'rows' => $rows));

		/*$m = $_SESSION['quote_email'];

		$result = db_query("SELECT * FROM free_quote WHERE email = '$m'");
		foreach($result as $t) {
			$html .= '<div class="">
				Submitted: '.date('m/d/y h:i:s', $t->created).'<br>
				Email: '.$m.'<br>
				'.$t->pid.'
				-------------------------------------
				<br>
			</div>';
		}*/

		$html .= '<div class="email-to" style="float:left;">
			<form id="form-send-mail" name="form-send-mail" style="margin-top20px;" method="post">
				<div class="form-item"><span class="label" style="color:#222;">Enter your email here:</span> 
					<input type="email" name="email" id="edit_email" required>
					<input type="submit" value="Submit" id="submit-email-button">
				</div>
			</form>
		</div>';

		if (isset($_POST['email'])) {
			if (valid_email_address($_POST['email'])) {
				$param = array();
				
				$param['body'] = 'Submitted: '.date('M d, Y h:i:s', time()).'<br>------------------------<br>'.$mail_body.'<br>
				<div>
		        <div><img src="http://decodoorware.co.za/sites/default/files/deco-doorware_3.png" width="250" /></div>
		        <div>Deco Doorware</div>
		        <div>Tel : +27 117953291</div>
		        <div>Sales : sales@decodoorware.co.za (link sends e-mail)</div>
		        <div>Contact : André du Toit</div>
		        <div>Mobile: +27 832358790</div>
		      </div>';
				//$param['body'] = http://www.decodoorware.co.za/print/my-quote;

				drupal_mail('free_quote', 'my_quote_email', $_POST['email'], language_default(), $param);
				drupal_set_message("Email has been sent!");
			} else {
				drupal_set_message("Invalid email address, please correct email and resubmit.");
			}
		}
	} else {
		$html = 'Please add products to your <a href="/free-quote">quote</a> first.';
		$flag = false;
	}

	if ($flag) {
		$html .= '<div style="float:right;margin-top: 40px;" class="quote-buttons">
				<a id="btn-submit-quote" type="button" href="#quote-form">Submit Quote</a>
				<a id="btn-submit-quote" type="button" href="/print/my-quote">Print</a>
			</div>

			<div style="display:none;">
				<div class="quote-form" id="quote-form">
					<form id="form-quote-form" name="form-quote-form">
						<div class="form-item"><span class="label">Full name:</span> 
							<input type="text" name="full_name" id="edit_full_name" required>
						</div>

						<div class="form-item"><span class="label">Email:</span> 
							<input type="email" name="email" id="edit_email" required>
						</div>

						<div class="form-item"><span class="label">Comment: </span>
							<textarea id="comment"></textarea>
						</div>

						<div class="form-item"><span class="label">&nbsp;</span>
							<input type="submit" value="Submit" id="submit-quote-button">
						</div>
					</form>
				</div>
			</div>';
	}

	return $html;
}

function free_quote_form_alter(&$form, &$form_state,$form_id ) {
	if ($form_id == "webform_client_form_30") {	
		$result = db_query("SELECT * FROM node WHERE type = 'product' AND status = 1 ORDER BY title ASC");
		$products = array();
		$products_string = '';
		foreach($result as $row) {
			$products[$row->title] = $row->title;
			$products_string .= trim($row->title).'|'.trim($row->title).PHP_EOL;
		}

		$form['submitted']['products']['#options'] = $products;
		$form['submitted']['products']['#webform_component']['extra']['items'] = $products_string;
		$form['submitted']['products']['#DANGEROUS_SKIP_CHECK'] = TRUE;
		$form['#node']->webform['components'][1]['extra']['items'] = $products_string;
	}
}

function _free_quote_submit() {
	session_start();

	if (isset($_POST['email']) && valid_email_address($_POST['email'])) {
		$owner = variable_get('site_mail', 'info@decodoorware.co.za');
		//$owner = 'zeroxw@gmail.com';
		$ids = trim($_POST['ids'], '|');
		$ids = explode('|', $ids);

		$quantities = trim($_POST['quantities'], '|');
		$quantities = explode('|', $quantities);

		$products_string = '';
		
		/*for($i = 0; $i < count($ids); $i++) {
			if ($ids[$i] && is_numeric($ids[$i])) {
				$n = node_load($ids[$i]);
				$products_string .= 'Product: '.$n->title.' | Quantity: '.$quantities[$i].'<br>';
			}
		}*/

		foreach($_SESSION['quote_list'] as $t => $v) {
			$n = node_load($t);
			$products_string = '<div>Product: '.$v[0].'</div>
			<div>Quantity: '.$v[1].'</div>';
		}

		$param = array();
		$param['body'] = 'Form submission: Free Quote<br>
		Submitted: '.date('M d, Y h:i:s', time()).'<br>
		Full name: '.$_POST['name'].'<br>
		Email: '.$_POST['email'].'<br>
		Comment: '.$_POST['comment'].'<br><br>
		Products:<br>
		------------------------<br>'.$products_string.'
		<br>
				<div>
		        <div><img src="http://decodoorware.co.za/sites/default/files/deco-doorware_3.png" width="250" /></div>
		        <div>Deco Doorware</div>
		        <div>Tel : +27 117953291</div>
		        <div>Sales : sales@decodoorware.co.za (link sends e-mail)</div>
		        <div>Contact : André du Toit</div>
		        <div>Mobile: +27 832358790</div>
		      </div>';
		//$owner = 'zeroxw@gmail.com';
		drupal_mail('free_quote', 'free_quote', $owner, language_default(), $param);

		db_insert('free_quote')
		->fields(array(
		  'email' => $_POST['email'],
		  'created' => time(),
		  'pid' => $products_string
		))->execute();

		$_SESSION['quote_email'] = $_POST['email'];

		print 1;
	} else {
		print 0;
	}

	exit();
}

function free_quote_mail($key, &$message, $params) {
    $language = $message['language'];
    switch ($key) {
        case 'free_quote':
            $message['subject'] = 'Form submission: Free Quote';
            $message['body'][] = $params['body'];
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
        break;

        case 'my_quote_email':
            $message['subject'] = 'My Quote';
            $message['body'][] = $params['body'];
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
        break;
    }
}

function _submit_quote_list() {
	if (!isset($_SESSION['quote_list'])) {
		print 'Please select product and add to quote list.';
	} else {
		$products_string = '';

		foreach($_SESSION['quote_list'] as $k => $v) {
			$n = node_load($k);
			$products_string .= 'Product: '.$n->title.' | Quantity: '.$v[1].'<br>';
		}

		$param = array();
		$param['body'] = 'Form submission: Free Quote<br>
		Submitted: '.date('M d, Y h:i:s', time()).'<br>
		Full name: '.$_POST['name'].'<br>
		Email: '.$_POST['email'].'<br>
		Comment: '.$_POST['comment'].'<br><br>
		Products:<br>
		------------------------<br>'.$products_string.'
		<br>
				<div>
		        <div><img src="http://decodoorware.co.za/sites/default/files/deco-doorware_3.png" width="250" /></div>
		        <div>Deco Doorware</div>
		        <div>Tel : +27 117953291</div>
		        <div>Sales : sales@decodoorware.co.za (link sends e-mail)</div>
		        <div>Contact : André du Toit</div>
		        <div>Mobile: +27 832358790</div>
		      </div>';
		$owner = variable_get('site_mail', 'info@decodoorware.co.za');
		//$owner = 'zeroxw@gmail.com';
		drupal_mail('free_quote', 'free_quote', $owner, language_default(), $param);

		unset($_SESSION['quote_list']);
		print 1;
	}

	drupal_exit();
}


function free_quote_block_info() {
	$blocks = array();
	
	$blocks['bolts_hooks_subcategories'] = array(
		'info' => 'Bolts & Hooks Subcategories',
		'status' => 0,		
	);

	$blocks['Handles_subcategories'] = array(
		'info' => 'Handles Subcategories',
		'status' => 0,		
	);

	$blocks['accessries_subcategories'] = array(
		'info' => 'Accessries Subcategories',
		'status' => 0,		
	);

	$blocks['vintage_range_subcategories'] = array(
		'info' => 'Vintage Range Subcategories',
		'status' => 0,		
	);

	return $blocks;
}

function free_quote_block_view($delta = '') {
	switch ($delta) {
		case 'bolts_hooks_subcategories':
			$block = array(
				'subject' => "Bolts & Hooks Subcategories",
				'content' => _subcategories(5)
			);
			return $block; break;

		case 'Handles_subcategories':
			$block = array(
				'subject' => "Bolts & Hooks Subcategories",
				'content' => _subcategories(2)
			);
			return $block; break;
		case 'accessries_subcategories':
			$block = array(
				'subject' => "Bolts & Hooks Subcategories",
				'content' => _subcategories(7)
			);
			return $block; break;
		case 'vintage_range_subcategories':
			$block = array(
				'subject' => "Vintage Range Subcategories",
				'content' => _subcategories(76)
			);
			return $block; break;
	}
}

function _subcategories($term) {
	$children = taxonomy_get_children($term);

	$html = '<div class="view view-products view-id-products">
    	<div class="view-content"><table class="views-view-grid cols-4"><tbody>';
	$index = 0;
	$row = 1;
	foreach($children as $t) {
		$index++;

		if ($index == 1) {
			$html .= '<tr class="row-'.$row.'">';
		}

		$uri = 'public://background.png';
		if (isset($t->field_picture['und'][0]['fid'])) {
			$uri = $t->field_picture['und'][0]['uri'];
		}

		$thumb = image_style_url("120", $uri);

		$html .= '<td class="col-'.$index.'">	
		  	<div class="views-field views-field-field-product-image" style="float: left; width: 100px;">
				<div class="field-content"><a href="/free-quote?field_category_tid='.$t->tid.'"><img alt="" src="'.$thumb.'" typeof="foaf:Image" class="mCS_img_loaded"></a>
				</div>
			</div>

			<div class="views-field views-field-title" style="float:left;">
		  		<span class="field-content"><a href="/free-quote?field_category_tid='.$t->tid.'">'.$t->name.'</a></span>
		  	</div>

		</td>';

		/*			
			<div class="views-field views-field-field-product-code">
				<span class="views-label views-label-field-product-code"></span>
				<div class="field-content"></div>
			</div>*/

		if ($index == 1) {
			$html .= '</tr>';
			$index = 0;
		}
		$row++;
	}

	$html .= '</tbody></table></div></div>';

	return $html;
}
